### PR TITLE
Added a pure numba hillshade that is 10x faster compared to numpy

### PR DESCRIPTION
**Pull request by a7az0th**
The new code uses less context switching and data transfers, minimizes communication overhead and removes the cupy dependency.  I've made it run by default, if cuda is available. Otherwise if falls back to numpy

This change addresses issue #541

### CODE REVIEW

**Comment by brendancol** [comment]
- [ ] change to I/O to cupy arrays

**Comment by brendancol** [comment]
@thuydotm can you review this and get back with any comments?

**Comment by thuydotm** [comment]
Thanks @a7az0th!
I think we can now remove the old `run_cupy` function and replace it with the `run_numba` since the old code is no longer called. `run_numba` should be renamed to `run_cupy` to be consistent with our coding convention. Otherwise looks good to me.

**Comment by a7az0th** [comment]
@thuydotm I've updated the source according to your feedback. I believe we can merge this.

**Comment by thuydotm** [comment]
Merged, thanks!

**Comment by a7az0th** [comment]
Thank you, too!

**Pull request merged**
