### PR TITLE
Test on Python 3.11

### LINKED ISSUE #743: Test Python 3.11 Support

### PR DESCRIPTION
**Pull request by thuydotm**
Fixes #743

### CODE REVIEW

**Comment by brendancol** [comment]
@thuydotm just to recap, this looks like an upstream issue with numba and we should keep our eye on development there.

**Comment by brendancol** [comment]
@thuydotm I think it is worth trying to re-run test and see if numba now works with PY3.11

**Comment by brendancol** [comment]
@thuydotm whats up with that crazy branch name `test_python3333333333`

**Comment by thuydotm** [comment]
That was an accident. Seems like I pressed and forgot to release the letter 3. All tests passed now and I think we can safely merge this MR. xarray-spatial finally supports Python 3.11.

**Review by brendancol — APPROVED** [review]
WOOOHOOOO!!!

**Pull request merged**
