### PR TITLE
add Github Action to publish package to PyPI

### PR DESCRIPTION
**Pull request by giancastro**
This PR solves the issue #359.

### CODE REVIEW

**Comment by brendancol** [comment]
@giancastro hey I added the `PYPI_API_TOKEN` secret to the repo

**Comment by giancastro** [comment]
@brendancol cool! is this PR ready to merge?

**Comment by giancastro** [comment]
@brendancol, could you add a new GitHub secret TEST_PYPI_API_TOKEN from test.pypi?

**Review by brendancol — COMMENTED** [review]
LGTM

**Pull request merged**
