### PR TITLE
fix tarball and drop versioneer

### PR DESCRIPTION
**Pull request by ocefpaf**
versioneer is deprecated, does not work properly with pep517/518, and the source distribution tarball on PyPI is broken without the versioneer.py file in it. See https://github.com/conda-forge/staged-recipes/pull/12177

This PR implements `setuptools_scm` instead of versioneer, modernize the Travis-CI a little bit and implement a tarball check to avoid regressions, and fix the tarball.

Ping @rsignell-usgs who requested the conda-forge package.

Needed in https://github.com/conda-forge/staged-recipes/pull/12177

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Fixes #12 also

**Comment by rsignell-usgs** [comment]
@brendancol, any chance of getting this merged?

**Comment by brendancol** [comment]
@rsignell-usgs @ocefpaf So amazing! Thank you guys so much for the contributions! Anything else we need to do to build for conda-forge?

**Comment by ocefpaf** [comment]
> @rsignell-usgs @ocefpaf So amazing! Thank you guys so much for the contributions!

BTW, most of the changes here are based on the [IOOS package skeleton](https://github.com/ioos/ioos-python-package-skeleton).

There are other things in there that you may want to use. Let me know if you have any suggestions too.

> Anything else we need to do to build for conda-forge?

You can issue a new release and I'll update the PR to [staged-recipes](https://github.com/conda-forge/staged-recipes/pull/12177).

**Comment by ocefpaf** [comment]
> You can issue a new release and I'll update the PR to staged-recipes.

I see you already did it! Working on the package now...

**Comment by brendancol** [comment]
Awesome thanks Filipe!  Also...great meeting you last fall in Ribeirão
Preto Python Brasil!

**Comment by ocefpaf** [comment]
> Awesome thanks Filipe! Also...great meeting you last fall in Ribeirão Preto Python Brasil!

Wait... We met! Sorry I did not recognize you from your GH avatar! Hope we can travel again one day and see each other in a conf somewhere.

**Pull request merged**
