### PR TITLE
GPU and Dask support for classify module

### PR DESCRIPTION
**Pull request by thuydotm**

### CODE REVIEW

**Comment by brendancol** [comment]
@thuydotm I think dask_gpu should work fine for this one, you may look at some examples in the multispectral PR

- [ ] add dask gpu test and implementation
- [ ] update readme table with green checks

**Comment by brendancol** [comment]
@thuydotm hey just remove the WIP from PR name when you want me to merge..

**Comment by brendancol** [comment]
@thuydotm hey hows it going on this?  Let's wrap up anything you are working on here and then start a new PR with any remaining classify tools

**Comment by thuydotm** [comment]
@brendancol we still have some more works related to adding numba implementation for some cupy case, and support dask numpy for natural breaks. They will come with other PR. This is now good to merge.

**Pull request merged**
