### PR TITLE
Use setuptools

### PR DESCRIPTION
**Pull request by giancastro**

### CODE REVIEW

**Comment by giancastro** [comment]
@thuydotm , this PR fixes #741. I had to remove the codebase tests, so we will need to add flake8 and isort to Github Actions.

**Comment by giancastro** [comment]
@thuydotm , we also need to test if `xrspatial.__version__` will work fine when installing from pypi and conda forge.

**Comment by thuydotm** [comment]
Thanks Gian! I can see all the jobs have run successfully. Going to merge this to have the build system work. Any idea why it suddenly failed before?

**Review by thuydotm — APPROVED** [review]

**Comment by giancastro** [comment]
No, I wasn't able to know the reason.

**Pull request merged**
